import request from "supertest";
import { createApp } from "@src/app.js";
import { db } from "@src/database/database.js";
import { ReadMachineService } from "@src/modules/machines/services/read.service.js";

describe("create machine", () => {
  it("should check user is authorized", async () => {
    const app = await createApp();
    // send request to create machine
    const response = await request(app).post("/v1/machines").send({});
    expect(response.statusCode).toEqual(401);
    expect(response.body.status).toBe("Unauthorized");
  });
  // it("should check user have permission to access", async () => {
  //   const app = await createApp();
  //   // get access token for authorization request
  //   const authResponse = await request(app).post("/v1/auth/signin").send({
  //     username: "user",
  //     password: "user2024",
  //   });
  //   const accessToken = authResponse.body.accessToken;
  //   // send request to create machine
  //   const response = await request(app).post("/v1/machines").send({}).set("Authorization", `Bearer ${accessToken}`);

  //   expect(response.statusCode).toEqual(403);
  //   expect(response.body.status).toBe("Forbidden Access");
  // });
  it("should save to database", async () => {
    const app = await createApp();
    // get access token for authorization request
    const authResponse = await request(app).post("/v1/auth/signin").send({
      username: "admin",
      password: "admin2024",
    });
    const accessToken = authResponse.body.accessToken;
    // send request to create machine
    const data = {
      name: "machine A",
    };
    const response = await request(app).post("/v1/machines").send(data).set("Authorization", `Bearer ${accessToken}`);
    // expected response status
    expect(response.statusCode).toEqual(201);
    // expected response body
    expect(response.body._id).not.toBeNull();
    // expected database data by user input
    const readMachineService = new ReadMachineService(db);

    const result = await readMachineService.handle(response.body._id);
    expect(String(result._id)).toEqual(response.body._id);
    expect(result.name).toEqual(data.name);
    // expected database data generated by system
    expect(result.createdAt instanceof Date).toBeTruthy();
    expect(String(result.createdBy_id)).toBe(authResponse.body._id);
  });
  it("should check required fields", async () => {
    const app = await createApp();
    // get access token for authorization request
    const authResponse = await request(app).post("/v1/auth/signin").send({
      username: "admin",
      password: "admin2024",
    });
    // send request to create machine
    const accessToken = authResponse.body.accessToken;

    // do not send all required fields
    const response = await request(app).post("/v1/machines").send({}).set("Authorization", `Bearer ${accessToken}`);
    expect(response.statusCode).toEqual(422);
    expect(response.body.status).toBe("Unprocessable Entity");
    expect(response.body.errors.name).toStrictEqual(["The name field is required."]);
  });
  it("should check unique fields", async () => {
    const app = await createApp();
    // get access token for authorization request
    const authResponse = await request(app).post("/v1/auth/signin").send({
      username: "admin",
      password: "admin2024",
    });
    const accessToken = authResponse.body.accessToken;
    // send request to create machine
    const data = {
      name: "machine A",
    };
    await request(app).post("/v1/machines").send(data).set("Authorization", `Bearer ${accessToken}`);
    const response = await request(app).post("/v1/machines").send(data).set("Authorization", `Bearer ${accessToken}`);

    expect(response.statusCode).toEqual(422);
    expect(response.body.status).toStrictEqual("Unprocessable Entity");
    expect(response.body.errors.name).toStrictEqual(["name is exists"]);
  });
});
